BugFix memory usage in Java, system.gc in predict pipeline

diff --git a/bin/pica-to-go b/bin/pica-to-go
--- a/bin/pica-to-go
+++ b/bin/pica-to-go
@@ -7,7 +7,8 @@ source "$CONFIG_FILE"
 
 #starts execution of pica-to-go and appends all cmd options to it
 function exec_app {
-	java $JAVA_HEAP_SPACE $ADDITIONAL_JVM_PARAMETERS -jar $DIR/$PICA_TO_GO_JAR $@ launcher
+	echo $JVM_SIZE #TODO:delete
+	java $JVM_SIZE $JAVA_HEAP_SPACE $ADDITIONAL_JVM_PARAMETERS -jar $DIR/$PICA_TO_GO_JAR $@ launcher
 }
 
 # CHECK FOR "GENERAL" DEPENDENCIES (e.g. coreutils commands, make)
@@ -44,18 +45,18 @@ function dependency_java {
 }
 
 
-#function dependency_python {
-#	local VERSION=$($PYTHON_PATH --version 2>&1 | cut -d ' ' -f 2 | cut -d '.' -f 1)
-#	local SUBVERSION=$($PYTHON_PATH --version 2>&1 | cut -d ' ' -f 2 | cut -d '.' -f 2)
-#	if [ $VERSION != "2" ]; then
-#		echo "#pica-to-go-launcher: Fatal Error: Python2 is not installed or callable via /usr/bin/python. Please install Python 2.7 or a newer Python2 version"
-#		exit 1
-#	fi
-#	if (($SUBVERSION < 7)); then
-#		echo "#pica-to-go-launcher: Fatal Error: Your Python2 version is outdated. Please install Python 2.7 or a newer Python2 version"
-#		exit 1
-#	fi
-#}
+function dependency_python {
+	local VERSION=$($PYTHON_PATH --version 2>&1 | cut -d ' ' -f 2 | cut -d '.' -f 1)
+	local SUBVERSION=$($PYTHON_PATH --version 2>&1 | cut -d ' ' -f 2 | cut -d '.' -f 2)
+	if [ $VERSION != "2" ]; then
+		echo "#pica-to-go-launcher: Fatal Error: Python2 is not installed or callable via /usr/bin/python. Please install Python 2.7 or a newer Python2 version"
+		exit 1
+	fi
+	if (($SUBVERSION < 7)); then
+		echo "#pica-to-go-launcher: Fatal Error: Your Python2 version is outdated. Please install Python 2.7 or a newer Python2 version"
+		exit 1
+	fi
+}
 
 
 function dependency_python_lib {
@@ -77,7 +78,7 @@ function mmseqs_version {
 	if (( $AVX2_SUPPORT > 0)); then
 		MMSEQS_VERSION="AVX2"
 	elif (( $SSE41_SUPPORT > 0)); then
-		local MMSEQS_VERSION="SSE41"	
+		MMSEQS_VERSION="SSE41"	
 	else
 		echo "#pica-to-go-launcher: Error: Your hardware does not support AVX2 or SSE4.1."
 		exit 1
@@ -86,12 +87,18 @@ function mmseqs_version {
 }
 
 
+function determine_jvm_size {
+	JVM_SIZE=$(awk '$1 ~ "MemTotal"{print $2}' /proc/meminfo)
+	JVM_SIZE="-Xmx${JVM_SIZE}K"
+	export JVM_SIZE
+}
+
 dependency_env
 dependency_java
-#TODO:include again (maybe change dependency python depending if pypy will be used)
-#dependency_python
+dependency_python
 dependency_python_lib
 mmseqs_version
+determine_jvm_size
 exec_app "$@"
 
 
